In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Red Wine Quality.csv")

In [3]:
df.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [10]:
df.shape

(1599, 12)

In [4]:
#check if null values are present
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [11]:
df.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [6]:
x=df.drop("quality",axis=1)
x.head()

fixed acidity  volatile acidity  citric acid  ...    pH  sulphates  alcohol
0            7.4              0.70         0.00  ...  3.51       0.56      9.4
1            7.8              0.88         0.00  ...  3.20       0.68      9.8
2            7.8              0.76         0.04  ...  3.26       0.65      9.8
3           11.2              0.28         0.56  ...  3.16       0.58      9.8
4            7.4              0.70         0.00  ...  3.51       0.56      9.4

[5 rows x 11 columns]

In [7]:
y=pd.DataFrame(df["quality"])
y.head()

quality
0        5
1        5
2        5
3        6
4        5

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.naive_bayes import GaussianNB
model_gnb=GaussianNB()
model_gnb.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [13]:
y_preds_gnb=model_gnb.predict(x_test)
y_preds_gnb

array([5, 5, 7, 5, 7, 5, 5, 6, 5, 5, 5, 5, 6, 4, 6, 7, 7, 6, 6, 5, 6, 5,
       6, 6, 6, 5, 5, 7, 5, 6, 6, 6, 5, 5, 6, 7, 5, 6, 8, 6, 5, 6, 7, 7,
       6, 5, 5, 6, 6, 7, 6, 6, 6, 7, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 6,
       5, 7, 6, 6, 5, 4, 5, 5, 5, 6, 5, 5, 5, 7, 6, 5, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 5, 6, 5, 7, 5, 7, 6, 5, 6, 7, 6, 6, 7, 6, 5, 6, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 6, 7, 6, 6, 5, 6, 4, 5, 8, 7, 5, 5, 6, 7, 5, 5,
       6, 6, 7, 5, 7, 4, 7, 6, 6, 5, 5, 6, 5, 6, 6, 7, 6, 6, 6, 6, 5, 5,
       6, 5, 6, 5, 6, 6, 6, 6, 7, 5, 7, 5, 6, 7, 5, 6, 7, 6, 5, 7, 6, 6,
       6, 7, 6, 5, 5, 8, 5, 7, 8, 5, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 5, 5, 5, 5, 5, 7, 6, 5, 6, 7, 4, 7, 5, 5, 6, 6, 6, 5,
       5, 6, 7, 6, 5, 7, 7, 6, 5, 6, 5, 6, 3, 6, 7, 6, 7, 7, 8, 7, 5, 4,
       5, 5, 6, 5, 6, 5, 4, 7, 5, 5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 8, 5, 6,
       5, 5, 6, 5, 5, 7, 6, 6, 6, 8, 7, 6, 7, 5, 7, 7, 5, 7, 6, 7, 6, 5,
       6, 5, 7, 6, 6, 4, 6, 5, 5, 6, 5, 6, 5, 5, 6,

In [16]:
from sklearn.metrics import accuracy_score
acc_gnb=accuracy_score(y_test,y_preds_gnb)
acc_gnb

0.5375

In [17]:
from sklearn.metrics import confusion_matrix
cm_gnb=confusion_matrix(y_test,y_preds_gnb)
cm_gnb

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  0,  7,  3,  0,  1],
       [ 2,  5, 86, 34,  8,  0],
       [ 0,  3, 33, 73, 29,  4],
       [ 1,  0,  0, 11, 13,  2],
       [ 0,  0,  0,  0,  3,  0]])

In [18]:
from sklearn.neighbors import KNeighborsClassifier
model_knn=KNeighborsClassifier()
model_knn.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [19]:
y_preds_knn=model_knn.predict(x_test)
y_preds_knn

array([5, 5, 7, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 7, 6, 5, 5, 7, 6,
       6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5,
       5, 6, 5, 6, 5, 6, 6, 5, 5, 7, 5, 5, 5, 5, 7, 5, 5, 6, 6, 5, 5, 5,
       5, 7, 7, 7, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 5, 5, 4, 6, 5, 5, 5, 5,
       6, 5, 5, 5, 5, 5, 4, 5, 5, 6, 5, 5, 7, 5, 5, 6, 6, 6, 6, 6, 6, 5,
       6, 5, 6, 6, 5, 6, 5, 7, 7, 6, 5, 7, 5, 5, 7, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 7, 5, 6, 5, 5, 6, 6,
       5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 7, 6, 7, 5, 6,
       5, 7, 6, 5, 5, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5,
       5, 5, 7, 6, 6, 5, 5, 5, 6, 4, 5, 6, 5, 5, 7, 6, 6, 6, 5, 6, 6, 5,
       6, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 7, 5, 6, 5, 5,
       5, 5, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 7, 6, 6, 5, 5, 5, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6,

In [20]:
from sklearn.metrics import accuracy_score
acc_knn=accuracy_score(y_test,y_preds_knn)
acc_knn

0.48125

In [21]:
from sklearn.metrics import confusion_matrix
cm_knn=confusion_matrix(y_test,y_preds_knn)
cm_knn

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  0, 10,  1,  0,  0],
       [ 0,  0, 90, 43,  2,  0],
       [ 0,  2, 74, 55, 11,  0],
       [ 0,  1,  4, 13,  9,  0],
       [ 0,  0,  0,  1,  2,  0]])